### ISSUE TITLE
Console command to add a color to MyColors?

### ISSUE THREAD

**Issue by sbolande** [Jtschwantes/Prysm#7]
Is there a way you could add a console command so I could create my own colors to use _between_ projects? Not really sure how feasible or needed that is, though.

**Comment by Jtschwantes** [comment]
That would definitely be possible; however, I feel it's out of the scope of this library.

The colors that are saved are really just escape character strings, so you could save those strings yourself however you'd like. They only render on the console when you change the console mode with `Initialize()`. You could print and save your colors if you want, or you could save the RGB values or the HEX value and use the functions to use them between projects. 

Does that resolve your concern?
